export const Questions = [
  {
    prompt: "What is the output of 1 + '1' in JavaScript?",
    optionA: "2",
    optionB: "'11'",
    optionC: "Error",
    optionD: "undefined",
    answer: "optionB",
  },
  {
    prompt: "Which of these is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    answer: "optionC",
  },
  {
    prompt: "Which of these is not a JavaScript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Django",
    answer: "optionD",
  },
  {
    prompt: "What is the time complexity of binary search in a sorted array?",
    optionA: "O(n)",
    optionB: "O(log n)",
    optionC: "O(1)",
    optionD: "O(n^2)",
    answer: "optionB",
  },
  {
    prompt: "Which HTTP status code indicates a successful request?",
    optionA: "200",
    optionB: "404",
    optionC: "500",
    optionD: "301",
    answer: "optionA",
  },
  {
    prompt: "What does CSS stand for?",
    optionA: "Cascading Style Sheets",
    optionB: "Computer Styling System",
    optionC: "Creative Style Scripts",
    optionD: "Cascading System Scripts",
    answer: "optionA",
  },
  {
    prompt: "What is the purpose of the 'use strict' directive in JavaScript?",
    optionA: "To enable modern syntax",
    optionB: "To enforce stricter parsing and error handling",
    optionC: "To run scripts faster",
    optionD: "To prevent CSS conflicts",
    answer: "optionB",
  },
  {
    prompt: "Which of these algorithms is used for sorting?",
    optionA: "Dijkstra's Algorithm",
    optionB: "Bubble Sort",
    optionC: "A* Search",
    optionD: "Depth First Search",
    answer: "optionB",
  },
  {
    prompt: "Which database uses a document-oriented model?",
    optionA: "MySQL",
    optionB: "MongoDB",
    optionC: "PostgreSQL",
    optionD: "SQLite",
    answer: "optionB",
  },
  {
    prompt: "What is the main difference between let and var in JavaScript?",
    optionA: "Scope handling",
    optionB: "Data type support",
    optionC: "Performance",
    optionD: "Both are identical",
    answer: "optionA",
  },
];
